# This file was created automatically with `myst init --gh-pages` ðŸª„ ðŸ’š
# Ensure your GitHub Pages settings for this repository are set to deploy with **GitHub Actions**.

name: Publish
on:
  push:
    # Runs on pushes targeting the default branch
    branches: [main]
env:
  # `BASE_URL` determines, relative to the root of the domain, the URL that your site is served from.
  # E.g., if your site lives at `https://mydomain.org/myproject`, set `BASE_URL=/myproject`.
  # If, instead, your site lives at the root of the domain, at `https://mydomain.org`, set `BASE_URL=''`.
  BASE_URL: /${{ github.event.repository.name }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache plugin drawio directory
        id: cache-drawio
        uses: actions/cache@v5
        with:
          path: ./book/_plugin/drawio
          key: drawio-${{ hashFiles('**/*.drawio') }}

      - name: Cache venv
        uses: actions/cache@v5
        with:
          path: venv
          key: venv-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Pages
        uses: actions/configure-pages@v3

      - name: Set up venv
        run: python3 -m venv venv

      - name: Pip install
        run: pip install -r requirements.txt

      - name: Pull draw.io docker image
        if: steps.cache-drawio.outputs.cache-hit != 'true'
        run: docker pull rlespinasse/drawio-desktop-headless

      - name: Build HTML Assets
        run: make build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./book/_build/html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Clear plugin dir on failure
        if: failure()
        run: rm -rf ./book/_plugin/*
